[package]
name = "rust_gen"
version = "0.1.0"
edition = "2021"

[dependencies]
opentelemetry = { version = "0.26", features = ["metrics"] }
opentelemetry_sdk = { version = "0.26", features = ["metrics", "rt-tokio"] }
opentelemetry-otlp = { version = "0.26", features = ["grpc-tonic", "metrics"] }
tokio = { version = "1", features = ["full"] }
